In [246]:
import pandas as pd
import pulp
from pulp import *

Reading the combined file

In [533]:
combined_pd = pd.read_csv('C:/Users/Arwa/Desktop/datasets/jobs_and_freelancers_combined_only_dollars.csv',delimiter=',',sep='\s*,\s*',
                           header=0,  encoding='utf-8', engine='python')

Display summary of fields

In [580]:
combined_pd.dtypes

taskID                                                     object
Freelancer_Name                                            object
Freelancer_username                                        object
Freelancer_Average_rating_for_all_completed_projects_x    float64
Freelancer_total_number_of_reviews_x                       object
Required_Skills 1                                          object
Required_Skills 2                                          object
Required_Skills 3                                          object
Required_Skills 4                                          object
Required_Skills 5                                          object
job_Status                                                 object
Job_url                                                    object
average_employer_rating_by_freelancers                    float64
Job_Budget                                                 object
wage                                                      float64
Freelancer_Average_rating_for_all_completed_projects_y    float64
job_completion_rate                                       float64
on_budget_rate                                            float64
on_time_rate                                              float64
repeat_hire_rate                                          float64
Freelancer_total_number_of_reviews_y                       object
Freelancer_location                                        object
Freelancer_education                                       object
skilks 1                                                   object
skilks 2                                                   object
skilks 3                                                   object
skilks 4                                                   object
skilks 5                                                   object
skilks 6                                                   object
skilks 7                                                   object
skilks 8                                                   object
skilks 9                                                   object
skilks 10                                                  object
dtype: object

Slice 10 records

In [535]:
data = combined_pd[0:10].copy()

data['Job_Budget']=15
data['Job_Budget']

0    15
1    15
2    15
3    15
4    15
5    15
6    15
7    15
8    15
9    15
Name: Job_Budget, dtype: int64

In [536]:
data.dtypes

taskID                                                     object
Freelancer_Name                                            object
Freelancer_username                                        object
Freelancer_Average_rating_for_all_completed_projects_x    float64
Freelancer_total_number_of_reviews_x                       object
Required_Skills 1                                          object
Required_Skills 2                                          object
Required_Skills 3                                          object
Required_Skills 4                                          object
Required_Skills 5                                          object
job_Status                                                 object
Job_url                                                    object
average_employer_rating_by_freelancers                    float64
Job_Budget                                                  int64
wage                                                      float64
Freelancer_Average_rating_for_all_completed_projects_y    float64
job_completion_rate                                       float64
on_budget_rate                                            float64
on_time_rate                                              float64
repeat_hire_rate                                          float64
Freelancer_total_number_of_reviews_y                       object
Freelancer_location                                        object
Freelancer_education                                       object
skilks 1                                                   object
skilks 2                                                   object
skilks 3                                                   object
skilks 4                                                   object
skilks 5                                                   object
skilks 6                                                   object
skilks 7                                                   object
skilks 8                                                   object
skilks 9                                                   object
skilks 10                                                  object
dtype: object


Tasks Set

In [537]:
# takes only tasks 
tasks = data[['taskID','Job_url','Job_Budget','Required_Skills 1','Required_Skills 2',
             'Required_Skills 3','Required_Skills 4','Required_Skills 5',
              'Freelancer_Average_rating_for_all_completed_projects_y']].copy()

tasks

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>taskID</th>
      <th>Job_url</th>
      <th>Job_Budget</th>
      <th>Required_Skills 1</th>
      <th>Required_Skills 2</th>
      <th>Required_Skills 3</th>
      <th>Required_Skills 4</th>
      <th>Required_Skills 5</th>
      <th>Freelancer_Average_rating_for_all_completed_projects_y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>t1</td>
      <td>https://www.freelancer.in/projects/Graphic-Des...</td>
      <td>15</td>
      <td>CSS</td>
      <td>Graphic Design</td>
      <td>Logo Design</td>
      <td>Photoshop</td>
      <td>WordPress</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>t2</td>
      <td>https://www.freelancer.in/projects/translation...</td>
      <td>15</td>
      <td>Arabic</td>
      <td>English Grammar</td>
      <td>Proofreading</td>
      <td>Report Writing</td>
      <td>Translation</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>t3</td>
      <td>https://www.freelancer.in/projects/threed-desi...</td>
      <td>15</td>
      <td>3D Design</td>
      <td>CAD/CAM</td>
      <td>Concept Design</td>
      <td>Manfactring</td>
      <td>Mechanical Engineering</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>t4</td>
      <td>https://www.freelancer.in/projects/Excel/gener...</td>
      <td>15</td>
      <td>Data Entry</td>
      <td>eCommerce</td>
      <td>Excel</td>
      <td>Translation</td>
      <td>WordPress</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>t5</td>
      <td>https://www.freelancer.in/projects/articles/Pr...</td>
      <td>15</td>
      <td>Article Writing</td>
      <td>Project Management</td>
      <td>Report Writing</td>
      <td>Research Writing</td>
      <td>Technical Writing</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>5</th>
      <td>t6</td>
      <td>https://www.freelancer.in/projects/articles/Pr...</td>
      <td>15</td>
      <td>Article Writing</td>
      <td>Project Management</td>
      <td>Report Writing</td>
      <td>Research Writing</td>
      <td>Technical Writing</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>6</th>
      <td>t7</td>
      <td>https://www.freelancer.in/projects/Data-Entry/...</td>
      <td>15</td>
      <td>Data Entry</td>
      <td>Photo Editing</td>
      <td>Photography</td>
      <td>Photoshop</td>
      <td>Web Search</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>t8</td>
      <td>https://www.freelancer.in/projects/Photoshop/P...</td>
      <td>15</td>
      <td>Data Entry</td>
      <td>Photo Editing</td>
      <td>Photography</td>
      <td>Photoshop</td>
      <td>Web Search</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>t9</td>
      <td>https://www.freelancer.in/projects/graphic-des...</td>
      <td>15</td>
      <td>Creative Design</td>
      <td>Graphic Design</td>
      <td>Icon Design</td>
      <td>Logo Design</td>
      <td>Photoshop Design</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>t10</td>
      <td>https://www.freelancer.in/projects/Translation...</td>
      <td>15</td>
      <td>English (UK)</td>
      <td>English (US)</td>
      <td>Indonesian</td>
      <td>Slogans</td>
      <td>Translation</td>
      <td>4.6</td>
    </tr>
  </tbody>
</table>
</div>

Workers Set

In [538]:
# takes only workers 
workers = data[['Freelancer_username','wage','skilks 1','skilks 2','skilks 3','skilks 4','skilks 5','skilks 6','skilks 7','skilks 8','skilks 9','skilks 10',
                'on_budget_rate','on_time_rate','repeat_hire_rate','job_completion_rate']].copy()

workers = workers.drop_duplicates()
workers

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Freelancer_username</th>
      <th>wage</th>
      <th>skilks 1</th>
      <th>skilks 2</th>
      <th>skilks 3</th>
      <th>skilks 4</th>
      <th>skilks 5</th>
      <th>skilks 6</th>
      <th>skilks 7</th>
      <th>skilks 8</th>
      <th>skilks 9</th>
      <th>skilks 10</th>
      <th>on_budget_rate</th>
      <th>on_time_rate</th>
      <th>repeat_hire_rate</th>
      <th>job_completion_rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>@AliChorov</td>
      <td>25.0</td>
      <td>Graphic Design</td>
      <td>Logo Design</td>
      <td>Photoshop</td>
      <td>Arts &amp; Crafts</td>
      <td>CSS</td>
      <td>Illustration</td>
      <td>WordPress</td>
      <td>Banner Design</td>
      <td>Animation</td>
      <td>Video Services</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.28</td>
      <td>0.99</td>
    </tr>
    <tr>
      <th>1</th>
      <td>@Aliserour</td>
      <td>10.0</td>
      <td>Translation</td>
      <td>Creative Writing</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.00</td>
      <td>1.00</td>
    </tr>
    <tr>
      <th>2</th>
      <td>@BuddhikaRapiD3D</td>
      <td>15.0</td>
      <td>CAD/CAM</td>
      <td>Mechanical Engineering</td>
      <td>Concept Design</td>
      <td>3D Design</td>
      <td>Manufacturing</td>
      <td>3D Modelling</td>
      <td>Product Design</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.08</td>
      <td>1.00</td>
    </tr>
    <tr>
      <th>3</th>
      <td>@DataWebServices</td>
      <td>7.0</td>
      <td>Data Entry</td>
      <td>Research</td>
      <td>Excel</td>
      <td>WordPress</td>
      <td>eCommerce</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.00</td>
      <td>1.00</td>
    </tr>
    <tr>
      <th>4</th>
      <td>@EbookWriter247</td>
      <td>5.0</td>
      <td>Research Writing</td>
      <td>Report Writing</td>
      <td>Article Writing</td>
      <td>Technical Writing</td>
      <td>Project Management</td>
      <td>Research</td>
      <td>Copywriting</td>
      <td>Article Rewriting</td>
      <td>Ghostwriting</td>
      <td>Business Analysis</td>
      <td>0.99</td>
      <td>0.92</td>
      <td>0.23</td>
      <td>0.90</td>
    </tr>
    <tr>
      <th>6</th>
      <td>@IvanchenkoTanya</td>
      <td>5.0</td>
      <td>Photoshop</td>
      <td>Photo Editing</td>
      <td>Photography</td>
      <td>Data Entry</td>
      <td>Web Search</td>
      <td>WordPress</td>
      <td>Illustrator</td>
      <td>Copy Typing</td>
      <td>3D Modelling</td>
      <td>NaN</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.30</td>
      <td>0.97</td>
    </tr>
    <tr>
      <th>8</th>
      <td>@SamDesigner1</td>
      <td>10.0</td>
      <td>Graphic Design</td>
      <td>Logo Design</td>
      <td>Icon Design</td>
      <td>Photoshop</td>
      <td>Creative Design</td>
      <td>Banner Design</td>
      <td>Photography</td>
      <td>Photoshop Design</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.00</td>
      <td>1.00</td>
    </tr>
    <tr>
      <th>9</th>
      <td>@SatrioHS</td>
      <td>12.0</td>
      <td>Translation</td>
      <td>Indonesian</td>
      <td>English (US)</td>
      <td>English (UK)</td>
      <td>Slogans</td>
      <td>Proofreading</td>
      <td>Editing</td>
      <td>Business Writing</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.00</td>
      <td>1.00</td>
      <td>0.18</td>
      <td>1.00</td>
    </tr>
  </tbody>
</table>
</div>

In [539]:
# Creates a list of the incoming tasks

In [540]:
# Creates a list of worker bool 
worker_bool = []
for worker in workers['Freelancer_username']:
    worker_bool.append(worker)
worker_bool

['@AliChorov',
 '@Aliserour',
 '@BuddhikaRapiD3D',
 '@DataWebServices',
 '@EbookWriter247',
 '@IvanchenkoTanya',
 '@SamDesigner1',
 '@SatrioHS']

Create Worker-Task-Values DataFrame

In [541]:
# duplicate the tasks by the number of workers 
in_task = []
for task in tasks['taskID']:
    #for i in range(0,len(worker_bool)):
        in_task.append(task)
in_task

['t1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9', 't10']

In [565]:
# create task values DataFrame
values = pd.DataFrame(columns=['taskID','Freelancer_username'])
# populate  the dataFrame
for task in in_task:
    for worker in worker_bool:
        values = values.append({'taskID':task, 'Freelancer_username':worker}, ignore_index=True)

values

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>taskID</th>
      <th>Freelancer_username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>t1</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>1</th>
      <td>t1</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>2</th>
      <td>t1</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>3</th>
      <td>t1</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>4</th>
      <td>t1</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>5</th>
      <td>t1</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>6</th>
      <td>t1</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>7</th>
      <td>t1</td>
      <td>@SatrioHS</td>
    </tr>
    <tr>
      <th>8</th>
      <td>t2</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>9</th>
      <td>t2</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>10</th>
      <td>t2</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>11</th>
      <td>t2</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>12</th>
      <td>t2</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>13</th>
      <td>t2</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>14</th>
      <td>t2</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>15</th>
      <td>t2</td>
      <td>@SatrioHS</td>
    </tr>
    <tr>
      <th>16</th>
      <td>t3</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>17</th>
      <td>t3</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>18</th>
      <td>t3</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>19</th>
      <td>t3</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>20</th>
      <td>t3</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>21</th>
      <td>t3</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>22</th>
      <td>t3</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>23</th>
      <td>t3</td>
      <td>@SatrioHS</td>
    </tr>
    <tr>
      <th>24</th>
      <td>t4</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>25</th>
      <td>t4</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>26</th>
      <td>t4</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>27</th>
      <td>t4</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>28</th>
      <td>t4</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>29</th>
      <td>t4</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>50</th>
      <td>t7</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>51</th>
      <td>t7</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>52</th>
      <td>t7</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>53</th>
      <td>t7</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>54</th>
      <td>t7</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>55</th>
      <td>t7</td>
      <td>@SatrioHS</td>
    </tr>
    <tr>
      <th>56</th>
      <td>t8</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>57</th>
      <td>t8</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>58</th>
      <td>t8</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>59</th>
      <td>t8</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>60</th>
      <td>t8</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>61</th>
      <td>t8</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>62</th>
      <td>t8</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>63</th>
      <td>t8</td>
      <td>@SatrioHS</td>
    </tr>
    <tr>
      <th>64</th>
      <td>t9</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>65</th>
      <td>t9</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>66</th>
      <td>t9</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>67</th>
      <td>t9</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>68</th>
      <td>t9</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>69</th>
      <td>t9</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>70</th>
      <td>t9</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>71</th>
      <td>t9</td>
      <td>@SatrioHS</td>
    </tr>
    <tr>
      <th>72</th>
      <td>t10</td>
      <td>@AliChorov</td>
    </tr>
    <tr>
      <th>73</th>
      <td>t10</td>
      <td>@Aliserour</td>
    </tr>
    <tr>
      <th>74</th>
      <td>t10</td>
      <td>@BuddhikaRapiD3D</td>
    </tr>
    <tr>
      <th>75</th>
      <td>t10</td>
      <td>@DataWebServices</td>
    </tr>
    <tr>
      <th>76</th>
      <td>t10</td>
      <td>@EbookWriter247</td>
    </tr>
    <tr>
      <th>77</th>
      <td>t10</td>
      <td>@IvanchenkoTanya</td>
    </tr>
    <tr>
      <th>78</th>
      <td>t10</td>
      <td>@SamDesigner1</td>
    </tr>
    <tr>
      <th>79</th>
      <td>t10</td>
      <td>@SatrioHS</td>
    </tr>
  </tbody>
</table>
<p>80 rows × 2 columns</p>
</div>

In [566]:
values.set_index(['taskID','Freelancer_username'],inplace=True) 
values.index

MultiIndex(levels=[['t1', 't10', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9'], ['@AliChorov', '@Aliserour', '@BuddhikaRapiD3D', '@DataWebServices', '@EbookWriter247', '@IvanchenkoTanya', '@SamDesigner1', '@SatrioHS']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 1, 1, 1, 1, 1, 1, 1, 1], [0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7]],
           names=['taskID', 'Freelancer_username'])

we calculate a task value for each incoming task.

The task value is associated with the estimated 
accuracy, skill fitness and cost of the task. The task value is calculated as a weighted linear combination of estimated accuracy, 
skill fitness (higher is better) and cost (lower is better).

populate  the values dataframe

In [567]:
import numpy as np
value =  np.random.random((80,))

values['task_value'] = value
       

values

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>task_value</th>
    </tr>
    <tr>
      <th>taskID</th>
      <th>Freelancer_username</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="8" valign="top">t1</th>
      <th>@AliChorov</th>
      <td>0.157328</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.254909</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.868076</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.037651</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.264565</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.392301</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.850856</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.985793</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t2</th>
      <th>@AliChorov</th>
      <td>0.412564</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.717046</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.823685</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.448993</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.349522</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.103514</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.578077</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.726884</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t3</th>
      <th>@AliChorov</th>
      <td>0.272046</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.135071</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.331177</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.550413</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.748517</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.779747</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.692309</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.161342</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">t4</th>
      <th>@AliChorov</th>
      <td>0.895352</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.581769</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.886084</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.343481</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.915023</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.363933</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">t7</th>
      <th>@BuddhikaRapiD3D</th>
      <td>0.303240</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.209863</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.331485</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.936095</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.707486</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.766852</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t8</th>
      <th>@AliChorov</th>
      <td>0.897245</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.516366</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.536444</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.873901</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.449013</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.219889</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.460934</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.430259</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t9</th>
      <th>@AliChorov</th>
      <td>0.327580</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.737044</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.031346</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.784636</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.442282</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.296911</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.238969</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.388160</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t10</th>
      <th>@AliChorov</th>
      <td>0.730520</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>0.424752</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>0.983858</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>0.861318</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>0.313567</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>0.439117</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>0.376094</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>0.653060</td>
    </tr>
  </tbody>
</table>
<p>80 rows × 1 columns</p>
</div>

 Model our decision variables using the LpVariable class

In [574]:
worker_status = pulp.LpVariable.dicts("worker_status",
                                     ((task_ID, Freelancer_username) for task_ID, Freelancer_username in values.index),
                                     cat='Binary')

instantiate a problem class, we’ll name it “LP_Optimization_Problem” and we’re looking for an optimal maximum so we use LpMaximize

Objective Function: 
//////////////////////

In [575]:
LP_Optimization_model = pulp.LpProblem("LP Optimization Problem", pulp.LpMaximize)

In [576]:
LP_Optimization_model += pulp.lpSum(
    [worker_status[task_ID, Freelancer_username] * values.loc[(task_ID, Freelancer_username), 'task_value'] 
     for task_ID, Freelancer_username in values.index])

Build constraints

In [577]:
 #number of tasks that the worker can be assigned to  must be between 0 and 3, or zero.
for task_ID, Freelancer_username in values.index:
    min_worker_tasks = 0
    max_worker_tasks = 1
    LP_Optimization_model += worker_status[(task_ID, Freelancer_username)] >= min_worker_tasks 
    LP_Optimization_model += worker_status[(task_ID, Freelancer_username)] <= max_worker_tasks

Solve the model

In [578]:
LP_Optimization_model.solve()
pulp.LpStatus[LP_Optimization_model.status]

'Optimal'

print the solution

In [579]:
output = []
for taskID, Freelancer_username in worker_status :
    var_output = {
        'taskID': taskID,
        'Freelancer_username': Freelancer_username,
        'worker_status': worker_status[(taskID, Freelancer_username)].varValue,
    }
    output.append(var_output)
output_df = pd.DataFrame.from_records(output).sort_values(['taskID', 'Freelancer_username'])
output_df.set_index(['taskID', 'Freelancer_username'], inplace=True)
output_df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>worker_status</th>
    </tr>
    <tr>
      <th>taskID</th>
      <th>Freelancer_username</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="8" valign="top">t1</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t10</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t2</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">t3</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">t6</th>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t7</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t8</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">t9</th>
      <th>@AliChorov</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@Aliserour</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@BuddhikaRapiD3D</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@DataWebServices</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@EbookWriter247</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@IvanchenkoTanya</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SamDesigner1</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>@SatrioHS</th>
      <td>1.0</td>
    </tr>
  </tbody>
</table>
<p>80 rows × 1 columns</p>
</div>